# **PyTorch Basics Tutorial**

### Check version

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms

print(torch.__version__)

1.5.1


### Tensors
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

### Creating Tensors from data
Tensors can be created from Python lists with the `torch.Tensor()` function.

In [2]:
# Example with 1-D data
data = [1, 2, 3]
tensor = torch.Tensor(data)
print("Example with 1-D data")
print(tensor)

# Example with 2-D data
data = [[1., 2., 3.], [4., 5., 6]]
tensor = torch.Tensor(data)
print("\nExample with 2-D data")
print(tensor)

# Example with 3-D data
data = [[[1.,2.], [3.,4.]],
        [[5.,6.], [7.,8.]]]
tensor = torch.Tensor(data)
print("\nExample with 3-D data")
print(tensor)

Example with 1-D data
tensor([1., 2., 3.])

Example with 2-D data
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Example with 3-D data
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


### Randomly initialized Tensor

In [3]:
x = torch.rand(3, 5)
print(x)

tensor([[0.0215, 0.1741, 0.4458, 0.4215, 0.8613],
        [0.4471, 0.0968, 0.0971, 0.8028, 0.1380],
        [0.0991, 0.7654, 0.0199, 0.7335, 0.2705]])


### Operations with Tensors
Most operations are very similar to NumPy.

In [4]:
# Addition
x = torch.Tensor([ 1., 2., 3. ])
y = torch.Tensor([ 4., 5., 6. ])

# using arithmetic operation
z = x + y
print(z)

# using method
print(torch.add(x, y))

# using method and providing an output tensor as argument
output = torch.empty(2, 3)
torch.add(x, y, out=output)
print(output)

tensor([5., 7., 9.])
tensor([5., 7., 9.])
tensor([5., 7., 9.])


### Perform automatic differentiation

In [ ]:
from torch.autograd import Variable
a = Variable(torch.Tensor([[1,2],[3,4]]), requires_grad=True)
print(a)
y = torch.sum(a**2) # 1 + 4 + 9 + 16 = 30
print(y)
y.backward()       # compute gradients of y wrt a
print(a.grad)      # print dy/da_ij = 2*a_ij for a_11, a_12, a21, a22

### Moving tensors around CPU / GPUs

In [ ]:
print(torch.cuda.is_available())

print(torch.cuda.device_count()) 

print(torch.cuda.get_device_name(0)) 

cuda0 = torch.device('cuda:0') #Performing the addition on GPU

a = torch.ones(3, 2, device=cuda0) #creating a tensor 'a' on GPU 
b = torch.ones(3, 2, device=cuda0) #creating a tensor 'b' on GPU 
c = a + b 
print(c) 

#As you can see the tensors are created on GPU and any operation you do on these tensors will be done on GPU.

#moving the result to cpu 
c = c.cpu()
print(c)